### ISSUE TITLE
android patch frida-server 成功后无法在android机上运行

### ISSUE THREAD

**Issue by seanchan** [suifei/fridare#10]
按文档./fridare.sh patch -m frida-server -latest -os android -arch arm64 -o ./patched进行魔改。
生成对应的魔改fridaserver后台push到安卓机上，运行直接抛出一堆二进制信息
使用命令file查看文件格式，提示：
$ file frida-server_xxxxx
frida-server_xxxxx: Mach-O 64-bit x86-64 executable

并非安卓arm64

**Comment by seanchan** [comment]
应该是-os -arch没生效导致的。

**Comment by seanchan** [comment]
./fridare.sh patch -m frida-server -latest -os android -arch arm64 -o ./patched
（直接下载了所有os，arch）后--->这一步我看也不应该？我多次运行，本地应该是有缓存的，脚本里的patch_frida_module 中存在重复下载 
下载完后，有如下日志输出：

[SUCC] 解压 frida-server-16.5.5-windows-x86_64.exe.xz 完成
[SUCC] 所有下载和解压操作完成
[INFO] 正在修补文件: ./patched/16.5.5/frida-server/macos/64/frida-server-16.5.5-macos-x86_64
[INFO] 使用指定的 Frida 魔改名: mtsvr
Detected file format: 1
MachO: CPU: x86_64, Byte Order: Little Endian, File Type: Exec
Replaced 17 occurrences
Successfully patched __cstring section
Replaced 9 occurrences
Successfully patched __const section
Patch success
Password:
[SUCC] 模块修补完成: ./patched/frida-server_mtsvr
mt:fridare $ file patched/frida-server_mtsvr 
patched/frida-server_mtsvr: Mach-O 64-bit executable x86_64

**Comment by sp4rkw** [comment]
这个提交是不是作者没合并，我也遇到了同样的情况
