### ISSUE TITLE
执行脚本后，frida丢失

### ISSUE THREAD

**Issue by liulep** [suifei/fridare#16]
环境：macos15
frida版本：16.5.6
问题：运行后，frida就找不到了
<img width="648" alt="截屏2024-11-01 19 36 28" src="https://github.com/user-attachments/assets/e313211c-e901-430c-a491-e791dd19d27a">
<img width="442" alt="截屏2024-11-01 19 36 48" src="https://github.com/user-attachments/assets/003f324f-dcac-4b2e-a854-36b13ade56af">

**Comment by No4l** [comment]
hello，请问下是怎么解决的？

**Comment by liulep** [comment]
> hello，请问下是怎么解决的？

没解决 用原版去了
