### ISSUE TITLE
frida符号还有残留

### ISSUE THREAD

**Issue by geekonion** [suifei/fridare#2]
大佬，首先感谢您的工作，太牛逼了
我尝试编译打包，然后调试了一下，发现仍然有残留的frida字符串（详见后文），想请教一下，是不是所有的这些frida相关的字符串都是可以替换的，或者说有没有不能替换的？

1. 编译日志：
./build.sh 16.3.3 27042 http://127.0.0.1:7890
期间可能会要求输入 sudo 密码，用于修改文件权限
Frida 版本：16.3.3
Frida 端口：27042
dpkg 已安装
本地存在 frida_16.3.3_iphoneos-arm.deb
正在修改 Frida 16.3.3 版本 (arm)
正在修改 plist 文件: frida_16.3.3_iphoneos-arm/Library/LaunchDaemons/re.frida.server.plist
FRIDA_NAME: akqhs
FRIDA_SERVER_PORT: 27042
plist 文件修改完成
plist 文件已重命名为: frida_16.3.3_iphoneos-arm/Library/LaunchDaemons/re.akqhs.server.plist
Launch daemon 修改完成
正在修改 DEBIAN 文件夹中的文件: frida_16.3.3_iphoneos-arm/DEBIAN
FRIDA_NAME: akqhs
修改 control 文件
修改 extrainst_ 文件
修改 prerm 文件
DEBIAN 文件夹中的文件修改完成
DEBIAN 文件修改完成
正在修改二进制文件: frida_16.3.3_iphoneos-arm/usr/sbin/frida-server
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Exec
Successfully patched __const section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Exec
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: E, Byte Order: Little Endian, File Type: Exec
Successfully patched __const section in architecture: CPU: ARM64, Subtype: E, Byte Order: Little Endian, File Type: Exec
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Exec
Successfully patched __const section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Exec
Patch success
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Dylib
Successfully patched __const section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Dylib
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Dylib
Successfully patched __const section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Dylib
Patch success
二进制文件修改完成
正在删除 frida_16.3.3_iphoneos-arm 中的 .DS_Store 文件...
.DS_Store 文件删除完成
dpkg-deb: 正在 'frida_16.3.3_iphoneos-arm_akqhs_tcp.deb' 中构建软件包 're.akqhs.server'。
Frida 16.3.3 版本 (arm) 修改完成
新版本名：akqhs
请使用新版本名：akqhs 进行调试
请使用端口：27042 进行调试
新版本 deb 文件：../dist/frida_16.3.3_iphoneos-arm_akqhs_tcp.deb
'-------------------------------------------------'
iPhone 安装：
scp dist/frida_16.3.3_iphoneos-arm_akqhs_tcp.deb root@<iPhone-IP>:/var/root
ssh root@<iPhone-IP>
dpkg -i /var/root/frida_16.3.3_iphoneos-arm_akqhs_tcp.deb
PC 连接：
frida -U -f com.xxx.xxx -l
frida -H <iPhone-IP>:27042 -f com.xxx.xxx --no-pause
'-------------------------------------------------'
本地存在 frida_16.3.3_iphoneos-arm64.deb
正在修改 Frida 16.3.3 版本 (arm64)
正在修改 plist 文件: frida_16.3.3_iphoneos-arm64/var/jb/Library/LaunchDaemons/re.frida.server.plist
FRIDA_NAME: akqhs
FRIDA_SERVER_PORT: 27042
plist 文件修改完成
plist 文件已重命名为: frida_16.3.3_iphoneos-arm64/var/jb/Library/LaunchDaemons/re.akqhs.server.plist
Launch daemon 修改完成
正在修改 DEBIAN 文件夹中的文件: frida_16.3.3_iphoneos-arm64/DEBIAN
FRIDA_NAME: akqhs
修改 control 文件
修改 extrainst_ 文件
修改 prerm 文件
DEBIAN 文件夹中的文件修改完成
DEBIAN 文件修改完成
正在修改二进制文件: frida_16.3.3_iphoneos-arm64/var/jb/usr/sbin/frida-server
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Exec
Successfully patched __const section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Exec
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: E, Byte Order: Little Endian, File Type: Exec
Successfully patched __const section in architecture: CPU: ARM64, Subtype: E, Byte Order: Little Endian, File Type: Exec
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Exec
Successfully patched __const section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Exec
Patch success
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Dylib
Successfully patched __const section in architecture: CPU: ARM64, Subtype: All, Byte Order: Little Endian, File Type: Dylib
Successfully patched __cstring section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Dylib
Successfully patched __const section in architecture: CPU: ARM64, Subtype: E_pauth0, Byte Order: Little Endian, File Type: Dylib
Patch success
二进制文件修改完成
正在删除 frida_16.3.3_iphoneos-arm64 中的 .DS_Store 文件...
.DS_Store 文件删除完成
dpkg-deb: 正在 'frida_16.3.3_iphoneos-arm64_akqhs_tcp.deb' 中构建软件包 're.akqhs.server'。
Frida 16.3.3 版本 (arm64) 修改完成
新版本名：akqhs
请使用新版本名：akqhs 进行调试
请使用端口：27042 进行调试
新版本 deb 文件：../dist/frida_16.3.3_iphoneos-arm64_akqhs_tcp.deb
'-------------------------------------------------'
iPhone 安装：
scp dist/frida_16.3.3_iphoneos-arm64_akqhs_tcp.deb root@<iPhone-IP>:/var/root
ssh root@<iPhone-IP>
dpkg -i /var/root/frida_16.3.3_iphoneos-arm64_akqhs_tcp.deb
PC 连接：
frida -U -f com.xxx.xxx -l
frida -H <iPhone-IP>:27042 -f com.xxx.xxx --no-pause
'-------------------------------------------------'
/Users/apple/Library/Python/3.9/lib/python/site-packages/frida/_frida.abi3.so
akqhs
Open Fat error: not a fat Mach-O file in record at byte 0x0
Successfully patched __cstring section in architecture: CPU: x86_64, Subtype: All, Byte Order: Little Endian, File Type: Bundle
Successfully patched __const section in architecture: CPU: x86_64, Subtype: All, Byte Order: Little Endian, File Type: Bundle
Patch success
Creating backup: /Users/apple/Library/Python/3.9/lib/python/site-packages/frida/core.py.fridare
Line 511: Replaced "frida:rpc" with "akqhs:rpc"
Line 554: Replaced "frida:rpc" with "akqhs:rpc"
Replacement complete
frida-tools 修改完成
2. frida-agent.dylib __TEXT.__cstring中的部分字符串：
rpc截图：
<img width="372" alt="图片" src="https://github.com/suifei/fridare/assets/12871217/c695577c-db77-4833-ae25-87baa4b2f749">

残留的字符串示例：
<img width="1116" alt="图片" src="https://github.com/suifei/fridare/assets/12871217/4b79e96e-d6d4-4717-a07b-d3172e488438">

**Comment by suifei** [comment]
是的，当前如果直接全部替换掉，需要验证和测试，目前只处理了经过测试过的；修改端口，文件名，路径，主要特征字串；
其它的字符串还需要测试，最近在完善工具，暂时还没有继续看这个部分，目前也能过不少探测
