### ISSUE TITLE
没有支持conda

### ISSUE THREAD

**Issue by Owen0225** [suifei/fridare#3]
我使用conda环境管理的frida版本，但是每次修改完都是修改我本机环境原生的东西，导致在conda环境中不生效的问题

**Comment by suifei** [comment]
嗯，我在新版本中已经支持不主动修改 原声环境的 frida-tools ；再增加一个指定位置的功能。

**Comment by suifei** [comment]
> 嗯，我在新版本中已经支持不主动修改 原声环境的 frida-tools ；再增加一个指定位置的功能。
我考虑了一下，这样并不是最好的方案，因为如果已经激活了 conda 环境，那么脚本确实应该自动适应到该环境，而不需要额外指定位置。让我来分析一下这个bug，看看为什么它不支持 conda 环境

**Comment by suifei** [comment]
### 3.0.1 Fixed
- 修复在 Conda 环境中无法正确识别和修改 Frida 工具的问题
- 解决多个 Python 环境共存时的兼容性问题
